// AUTO-GENERATED by perf-probe/generate.ts — do not edit by hand
// axis=eventbus-listener-leak N=10
import { test, expect } from "bun:test";
import { onStateChanged } from "../eventBus";

test("eventbus-listener-leak-0", () => { onStateChanged(() => {}); expect(1).toBe(1); });
test("eventbus-listener-leak-1", () => { onStateChanged(() => {}); expect(1).toBe(1); });
test("eventbus-listener-leak-2", () => { onStateChanged(() => {}); expect(1).toBe(1); });
test("eventbus-listener-leak-3", () => { onStateChanged(() => {}); expect(1).toBe(1); });
test("eventbus-listener-leak-4", () => { onStateChanged(() => {}); expect(1).toBe(1); });
test("eventbus-listener-leak-5", () => { onStateChanged(() => {}); expect(1).toBe(1); });
test("eventbus-listener-leak-6", () => { onStateChanged(() => {}); expect(1).toBe(1); });
test("eventbus-listener-leak-7", () => { onStateChanged(() => {}); expect(1).toBe(1); });
test("eventbus-listener-leak-8", () => { onStateChanged(() => {}); expect(1).toBe(1); });
test("eventbus-listener-leak-9", () => { onStateChanged(() => {}); expect(1).toBe(1); });
