// perf-probe ダミーテスト生成スクリプト
//
// 使い方: cd skills/cmux-team/manager && bun run perf-probe/generate.ts
//
// T337 / A021 仮説検証用。生成物は perf-probe/<axis>-N<N>.probe.ts。
// `.probe.ts` は bun の auto-discovery (*.test.ts / *.spec.ts) に拾われないため
// 本番テスト群とは分離される。明示パスで実行することのみ可能。

import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));

type Axis =
  | "baseline"
  | "eventbus"
  | "eventbus-emit"
  | "eventbus-listener-leak"
  | "eventbus-listener-emit"
  | "sqlite-close"
  | "sqlite-leak"
  | "spawn";

const SIZES = [10, 50, 200] as const;
const AXES: Axis[] = [
  "baseline",
  "eventbus",
  "eventbus-emit",
  "eventbus-listener-leak",
  "eventbus-listener-emit",
  "sqlite-close",
  "sqlite-leak",
  "spawn",
];

function header(axis: Axis, n: number): string {
  return `// AUTO-GENERATED by perf-probe/generate.ts — do not edit by hand\n// axis=${axis} N=${n}\n`;
}

function bodyBaseline(n: number): string {
  let out = `import { test, expect } from "bun:test";\n\n`;
  for (let i = 0; i < n; i++) {
    out += `test("baseline-${i}", () => { expect(1).toBe(1); });\n`;
  }
  return out;
}

function bodyEventbus(n: number): string {
  // module-level import の副作用だけを起こすケース。emit はしない。
  let out = `import { test, expect } from "bun:test";\nimport "../eventBus";\n\n`;
  for (let i = 0; i < n; i++) {
    out += `test("eventbus-${i}", () => { expect(1).toBe(1); });\n`;
  }
  return out;
}

function bodyEventbusEmit(n: number): string {
  // 各 it で notifyStateChanged を 1 回呼ぶケース。listener は登録しない。
  let out = `import { test, expect } from "bun:test";\nimport { notifyStateChanged } from "../eventBus";\n\n`;
  for (let i = 0; i < n; i++) {
    out += `test("eventbus-emit-${i}", () => { notifyStateChanged("probe-${i}"); expect(1).toBe(1); });\n`;
  }
  return out;
}

function bodyEventbusListenerLeak(n: number): string {
  // 各 it で onStateChanged で listener 登録し、戻り値の dispose を呼ばない。
  // listener はプロセス内で累積していく。emit はしない。
  let out = `import { test, expect } from "bun:test";\nimport { onStateChanged } from "../eventBus";\n\n`;
  for (let i = 0; i < n; i++) {
    out += `test("eventbus-listener-leak-${i}", () => { onStateChanged(() => {}); expect(1).toBe(1); });\n`;
  }
  return out;
}

function bodyEventbusListenerEmit(n: number): string {
  // 各 it で listener を登録し（dispose しない）、emit する。
  // listener が累積した状態で emit するため、k 番目の emit で k 個の listener が呼ばれる
  // → 同一プロセス内で累積した場合に O(N^2) 的振る舞いを期待。
  let out = `import { test, expect } from "bun:test";\nimport { onStateChanged, notifyStateChanged } from "../eventBus";\n\n`;
  for (let i = 0; i < n; i++) {
    out += `test("eventbus-listener-emit-${i}", () => { onStateChanged(() => {}); notifyStateChanged("p"); expect(1).toBe(1); });\n`;
  }
  return out;
}

function bodySqliteClose(n: number): string {
  let out = `import { test, expect } from "bun:test";\nimport { Database } from "bun:sqlite";\n\n`;
  for (let i = 0; i < n; i++) {
    out += `test("sqlite-close-${i}", () => { const db = new Database(":memory:"); db.close(); expect(1).toBe(1); });\n`;
  }
  return out;
}

function bodySqliteLeak(n: number): string {
  let out = `import { test, expect } from "bun:test";\nimport { Database } from "bun:sqlite";\n\n`;
  for (let i = 0; i < n; i++) {
    out += `test("sqlite-leak-${i}", () => { new Database(":memory:"); expect(1).toBe(1); });\n`;
  }
  return out;
}

function bodySpawn(n: number): string {
  let out = `import { test, expect } from "bun:test";\n\n`;
  for (let i = 0; i < n; i++) {
    out += `test("spawn-${i}", async () => { await Bun.spawn(["echo","x"]).exited; expect(1).toBe(1); });\n`;
  }
  return out;
}

function bodyFor(axis: Axis, n: number): string {
  switch (axis) {
    case "baseline":
      return bodyBaseline(n);
    case "eventbus":
      return bodyEventbus(n);
    case "eventbus-emit":
      return bodyEventbusEmit(n);
    case "eventbus-listener-leak":
      return bodyEventbusListenerLeak(n);
    case "eventbus-listener-emit":
      return bodyEventbusListenerEmit(n);
    case "sqlite-close":
      return bodySqliteClose(n);
    case "sqlite-leak":
      return bodySqliteLeak(n);
    case "spawn":
      return bodySpawn(n);
  }
}

function main(): void {
  for (const axis of AXES) {
    for (const n of SIZES) {
      const path = join(HERE, `${axis}-N${n}.probe.ts`);
      const content = header(axis, n) + bodyFor(axis, n);
      writeFileSync(path, content);
      console.log(`wrote ${path} (${content.length} bytes)`);
    }
  }
}

main();
