// AUTO-GENERATED by perf-probe/generate.ts — do not edit by hand
// axis=spawn N=10
import { test, expect } from "bun:test";

test("spawn-0", async () => { await Bun.spawn(["echo","x"]).exited; expect(1).toBe(1); });
test("spawn-1", async () => { await Bun.spawn(["echo","x"]).exited; expect(1).toBe(1); });
test("spawn-2", async () => { await Bun.spawn(["echo","x"]).exited; expect(1).toBe(1); });
test("spawn-3", async () => { await Bun.spawn(["echo","x"]).exited; expect(1).toBe(1); });
test("spawn-4", async () => { await Bun.spawn(["echo","x"]).exited; expect(1).toBe(1); });
test("spawn-5", async () => { await Bun.spawn(["echo","x"]).exited; expect(1).toBe(1); });
test("spawn-6", async () => { await Bun.spawn(["echo","x"]).exited; expect(1).toBe(1); });
test("spawn-7", async () => { await Bun.spawn(["echo","x"]).exited; expect(1).toBe(1); });
test("spawn-8", async () => { await Bun.spawn(["echo","x"]).exited; expect(1).toBe(1); });
test("spawn-9", async () => { await Bun.spawn(["echo","x"]).exited; expect(1).toBe(1); });
