// AUTO-GENERATED by perf-probe/generate.ts — do not edit by hand
// axis=sqlite-leak N=10
import { test, expect } from "bun:test";
import { Database } from "bun:sqlite";

test("sqlite-leak-0", () => { new Database(":memory:"); expect(1).toBe(1); });
test("sqlite-leak-1", () => { new Database(":memory:"); expect(1).toBe(1); });
test("sqlite-leak-2", () => { new Database(":memory:"); expect(1).toBe(1); });
test("sqlite-leak-3", () => { new Database(":memory:"); expect(1).toBe(1); });
test("sqlite-leak-4", () => { new Database(":memory:"); expect(1).toBe(1); });
test("sqlite-leak-5", () => { new Database(":memory:"); expect(1).toBe(1); });
test("sqlite-leak-6", () => { new Database(":memory:"); expect(1).toBe(1); });
test("sqlite-leak-7", () => { new Database(":memory:"); expect(1).toBe(1); });
test("sqlite-leak-8", () => { new Database(":memory:"); expect(1).toBe(1); });
test("sqlite-leak-9", () => { new Database(":memory:"); expect(1).toBe(1); });
