// AUTO-GENERATED by perf-probe/generate.ts — do not edit by hand
// axis=sqlite-close N=10
import { test, expect } from "bun:test";
import { Database } from "bun:sqlite";

test("sqlite-close-0", () => { const db = new Database(":memory:"); db.close(); expect(1).toBe(1); });
test("sqlite-close-1", () => { const db = new Database(":memory:"); db.close(); expect(1).toBe(1); });
test("sqlite-close-2", () => { const db = new Database(":memory:"); db.close(); expect(1).toBe(1); });
test("sqlite-close-3", () => { const db = new Database(":memory:"); db.close(); expect(1).toBe(1); });
test("sqlite-close-4", () => { const db = new Database(":memory:"); db.close(); expect(1).toBe(1); });
test("sqlite-close-5", () => { const db = new Database(":memory:"); db.close(); expect(1).toBe(1); });
test("sqlite-close-6", () => { const db = new Database(":memory:"); db.close(); expect(1).toBe(1); });
test("sqlite-close-7", () => { const db = new Database(":memory:"); db.close(); expect(1).toBe(1); });
test("sqlite-close-8", () => { const db = new Database(":memory:"); db.close(); expect(1).toBe(1); });
test("sqlite-close-9", () => { const db = new Database(":memory:"); db.close(); expect(1).toBe(1); });
